### ISSUE TITLE
Support biosboot partition type

### ISSUE THREAD

**Issue by jrha** [quattor/ncm-lib-blockdevices#49]
When installing GRUB2 on a disk that uses the GUID Partition Table (GPT) with a legacy (non-UEFI) BIOS or a UEFI BIOS booted in legacy mode, a special 1MB partition should be created to hold the stage2 image. This was not an issue with earlier versions of GRUB as the complete payload was able to fit in the boot loader segment.

This requirement is enforced by SL7+ versions of Anaconda, so can be a blocker to deploying SL7 in certain configurations.

If the system has a UEFI BIOS **and** is installed using UEFI netboot an EFI System partition of at least 100MB should be created instead.

**Comment by jrha** [comment]
Supporting this could be as simple as adding a line similar to the following to the kickstart file.
```
part biosboot --onpart sda1 --fstype=biosboot
```

**Comment by stdweird** [comment]
euhm, why the issue in this repo? sounds like a AII issue (but we have been using `biosboot` for almost a year with `ncm-lib-blockdevices`)

**Comment by jrha** [comment]
How?

**Comment by stdweird** [comment]
according to our templates, you make a 1 MB partition and set the `bios_grub` flag
```pan
SELF['sda4']['flags'] = nlist("bios_grub", true);
```
(https://github.com/quattor/template-library-core/blob/master/quattor/blockdevices.pan#L25)

also see https://github.com/quattor/ncm-lib-blockdevices/pull/31

**Comment by stdweird** [comment]
@jrha do you use partitoning in `%pre` or is it pure anaconda via ks commands?

**Comment by jrha** [comment]
Hmpf, I couldn't find that :disappointed: we use `%pre` partitioning.

**Comment by stdweird** [comment]
@jrha i also had to look it up in our templates
well, biosboot in itself doesn't exist; but it might make sense to add a function `mkbiosboot` in the coretemplates that creates a 1 MB partiton and sets this flag.

do you have any info on the ` EFI System partition`? i have no clue what that is.

**Comment by jrha** [comment]
I haven't managed to get a UEFI image to boot yet, but it is supposed to be a FAT-derived area for all OSes on a system to store bootloader payloads.

**Comment by stdweird** [comment]
UEFI pxebooting is on my todo list for the coming month :smile:

**Comment by jrha** [comment]
I can successfully cause a Dell BIOS to dump a stack trace, but not boot.

**Comment by jrha** [comment]
Ok, there's definitely a bug somewhere, creating 1MB or 2MB partitions fails (I think the partition maths breaks down), creating a 100MB biosboot partition does work, but seems like a waste. How big are your biosboot partitions?

**Comment by stdweird** [comment]
you also need to force an offset if i remeber correctly, let me check

**Comment by stdweird** [comment]
this is the config we use on our ceph boxes
```pan
prefix '/system/blockdevices';
variable CEPH_SSD_DISKS = list('sda', 'sdb');
# Boot disk partitions
'partitions' = {
    foreach(idx;disk;CEPH_SSD_DISKS){
        partitions_add(disk, nlist(
            format('%s1', disk), 256*MB,
            format('%s2', disk), 20*GB,
            format('%s3', disk), DISK_SWAP_SIZE,
            format('%s4', disk), 1*MB, #biosboot
            format('%s5', disk), 10*GB,
            format('%s6', disk), 10*GB,
            format('%s7', disk), -1));
        SELF[format('%s1', disk)]['offset'] = 1;
    };
    SELF['sda4']['flags'] = nlist("bios_grub", true);
    SELF;
};
```

**Comment by stdweird** [comment]
the `offset` is indeed needed for inprecise parted math, it was introduced in https://github.com/quattor/ncm-lib-blockdevices/pull/24/files

**Comment by jrha** [comment]
Oh and it appears we are doing the file systems twice, both `%pre` and anaconda are running `mkfs`, so that's fun.

**Comment by stdweird** [comment]
for `/` it's normal in el7. it seemed the only way at the time with 7.0. haven't retried yet.
