### ISSUE TITLE
creating software raids on partitions of gpt disk triggers bug

### ISSUE THREAD

**Issue by kwaegema** [quattor/ncm-lib-blockdevices#54]
On https://github.com/quattor/ncm-lib-blockdevices/blob/9344da85f7874d0b30815a9f992d9a2b477336c1/src/main/perl/MD.pm#L317

fdisk is run for the devices of the raid array.
Now, when these devices are large gpt partitions, something happens:

 AII: WARNING: The size of this disk is 4.0 TB (4000787030016 bytes).
AII: DOS partition table format can not be used on drives for volumes
AII: larger than (2199023255040 bytes) for 512-byte sectors. Use parted(1) and GUID 
AII: partition table format (GPT).

AII: Welcome to fdisk (util-linux 2.23.2).
kernel: [  496.235254]  sdc: sdc1
AII: Changes will remain in memory only, until you decide to write them.
AII: Be careful before using the write command.
AII: Command (m for help): Selected partition 1
AII: Hex code (type L to list all codes): Changed type of partition 'GPT' to 'XENIX root'
...
Fdisk lists only one partition. Because it sees only one partition, it selects the partition itself. So instead of giving the 'fd' hex code , it gives the partition number '2' to the command, and this changes the partition type to XENIX root. Then it writes the partition table with only one partition in it (so my other partitions are gone ) and a wrong partition type

So fdisk really should not be used for gpt partitions larger then 2G. I guess for these we should implement another way with parted ?

**Comment by jrha** [comment]
Ugh. We should avoid using `fdisk` wherever we can use `parted` instead.

**Comment by kwaegema** [comment]
fixed by #55

**Comment by jrha** [comment]
Closed in #56.
