### ISSUE TITLE
MD: creating named devices on el7 should happen in /dev/md instead of /dev/

### ISSUE THREAD

**Issue by kwaegema** [quattor/ncm-lib-blockdevices#55]
mdadm complains that /dev/mdDEVNAME is not a valid name, and it should be /dev/md/DEVNAME.

**Comment by kwaegema** [comment]
you can do /dev/mdNNN, but if you want to specify names, it has to be under /dev/md/

**Comment by kwaegema** [comment]
#56 makes this possible (albeit not the most clean way, you have to escape it in the profiles, but it is the least intrusive)

**Comment by stdweird** [comment]
@kwaegema can you maybe add an example here?
