### ISSUE TITLE
support efi partition

### ISSUE THREAD

**Issue by stdweird** [quattor/ncm-lib-blockdevices#81]
We need a new partition type `efi`, should do the following
* in `%pre`, create a vfat partiton
* in ks, create a `--fstype efi`, and let anacomnda reformat the partition again (like `/` on el7).

We will need this type also in core templates.

This is related to https://github.com/quattor/aii/pull/225

**Comment by stdweird** [comment]
@jouvin imho this should be resolved also to make it part of the release (but not so much work)

**Comment by jouvin** [comment]
@stdweird the template library part has already been existed for a while... This is in the `standard` part of the template library (handled by `filesystem/config`). I don't know why you want to add something to `ncm-lib-blockdevices`: the current version works perfectly with the template library, including for the creation of this `bios_grub` partition.

**Comment by stdweird** [comment]
@jouvin afaik, bios_grub is for gpt partitions with legacy bios. uefi needs a 100MB vfat partiton, but there's something magical about anaconda that it can't use it as such (needs the `-fstype efi`)

**Comment by jouvin** [comment]
No `bios_grub` is for UEFI (for legacy BIOS this is `biosboot`)... if I'm right! I'm sure I tested (more than once) the installation of a system with this configuration last Fall when I did all the tests before starting the implementation... And with the suggested variable (see the AII doc about UEFI), it creates a 200 MB partition. Anaconda may have some magic but I am not sure we need it: at least we can live with what we have now and refine it later (feel free to add this to https://github.com/quattor/aii/issues/255.

**Comment by stdweird** [comment]
parted https://www.gnu.org/software/parted/manual/html_node/set.html is very clear. it looks like we need the `esp` flag (not supported in schema), but it's an alias to boot on gpt. i'll give it a try.
i've inspected a system that has uefi, it only has a boot flag set on the efi partiton, no other flags. (the system was deployed with xcat)

**Comment by stdweird** [comment]
parrted line
```
 2      21.5GB  21.7GB  210MB   fat16           EFI System Partition  boot
```

fstab entry (has special mountopts)
```
UUID=123          /boot/efi               vfat    defaults,uid=0,gid=0,umask=0077,shortname=winnt 0 0
```

**Comment by jrha** [comment]
From my desktop (UEFI and kernel 4.4.0-64):

fstab:
```
UUID=E35F-1B9A        /boot/efi       vfat    defaults        0       1
```
mtab:
```
/dev/sda1 /boot/efi vfat rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro 0 0
```

**Comment by stdweird** [comment]
to confirm that `vfat` with `boot` flag is working on `gpt`. i guess we only need to add support for `esp` flag, so uefi on non-gpt also works

this is a non-issue
