### ISSUE TITLE
kickstart configuration of logvol is incomplete on SL7

### ISSUE THREAD

**Issue by nowack73** [quattor/ncm-lib-blockdevices#82]
I generate kickstart files for the installation of SL7.3 using version 17.2 of ncm-lib-blockdevices. 

The kickstart file contains two lines that are wrong according to anaconda:

```
logvol / --vgname=vg.01 --name=root --fstype=ext4 --fsoptions='defaults'
```
```
logvol swap --vgname=vg.01 --name=swap --fstype=swap --fsoptions='defaults'
```

They are produced by [ksfsformat in Blockdevices.pm](https://github.com/quattor/ncm-lib-blockdevices/blob/master/src/main/perl/Blockdevices.pm#L403).

Adding "--useexisting" to both lines makes anaconda happy. 

With SL6, "--useexisiting" is not necessary, but according to the documentation this option is available.

**Comment by stdweird** [comment]
@nowack73 this is seriously strange. are `/` and swap created in `%pre` in your case?

for "normal" partitions, when swap and / were created in %pre, anaconda failed when using `--useexisting` in el7. but it seems that for / and swap on logical volumes, they have to be reused?

**Comment by nowack73** [comment]
Here is an update: Now I have used SL7.4 and Quattor 17.8.
Anaconda complains about missing "--size" arguments in the kickstart file if I want to use logical volumes created by the %pre script. For "logvol" in SL7, "--size" or "--useexisting" are mandatory.

If I modify LV.pm (analogous to MD.pm) anaconda is happy:
```diff
diff --git a/src/main/perl/LV.pm b/src/main/perl/LV.pm
index d57f7f6..3db18a9 100644
--- a/src/main/perl/LV.pm
+++ b/src/main/perl/LV.pm
@@ -380,9 +380,18 @@ sub print_ks
     $self->{volume_group}->print_ks;
     print "\n";
 
+    ###
+    my $useexisting = '';
+    if ($fs->{useexisting_md}) {
+        $self->debug(5, 'useexisting flag enabled');
+        $useexisting = "--useexisting";
+    }
+    ###
     print join(" ",
         "logvol", $fs->{mountpoint}, "--vgname=$self->{volume_group}->{devname}
-        "--name=$self->{devname}", $self->ksfsformat($fs), "\n");
+        "--name=$self->{devname}", $self->ksfsformat($fs),
+        $useexisting, ###
+        "\n");
 }
 
This results in a kickstart file like this:
```
part /boot --onpart vda1 --noformat

volgroup vg.01 --noformat

logvol / --vgname=vg.01 --name=root --fstype=ext4 --fsoptions='defaults' --useexisting

volgroup vg.01 --noformat

logvol swap --vgname=vg.01 --name=swap --fstype=swap --fsoptions='defaults' --useexisting

volgroup vg.01 --noformat

logvol /home --vgname=vg.01 --name=home --noformat --useexisting

volgroup vg.01 --noformat

logvol /opt --vgname=vg.01 --name=opt --noformat --useexisting

volgroup vg.01 --noformat

logvol /tmp --vgname=vg.01 --name=tmp --noformat --useexisting

volgroup vg.01 --noformat

logvol /var --vgname=vg.01 --name=var --noformat --useexisting

volgroup vg.01 --noformat

logvol /data --vgname=vg.01 --name=data --noformat --useexisting
```

**Comment by stdweird** [comment]
@nowack73 just to be clear, with this patch, you also need to modify your templates to set the flag.

**Comment by stdweird** [comment]
@nowack73 ignore that. aii sets this attribute also.
