### ISSUE TITLE
invalid ciss partition support?

### ISSUE THREAD

**Issue by stdweird** [quattor/ncm-lib-blockdevices#83]
Is https://github.com/quattor/ncm-lib-blockdevices/blob/master/src/main/perl/Partition.pm#L132 correct? (i'm aware of `cciss` (2 `c`s); and also the explicit `+` in the device name looks odd).

**Comment by jrha** [comment]
@stdweird ­— are you referring to https://github.com/quattor/ncm-lib-blockdevices/blob/83d1988dc609a30ed83850820550cf4e9225fa72/src/main/perl/Partition.pm#L140?
I think the Line has moved since your original comment (it helps to link to a specific version of the file).

**Comment by jrha** [comment]
If https://github.com/torvalds/linux/blob/5d812b47a668f539f763a9e95167fd2bdf488a7a/Documentation/blockdev/cciss.txt is to be believed, I think the regex should be `(/dev/cciss/c\d+d\d+)p\d+`

**Comment by jrha** [comment]
A quick grep of the kernel documentation indicates that these are the only valid blockdevice name forms produced by the mainline code (external modules be damned):

```
/dev/cciss
/dev/cciss/c0d0
/dev/cciss/c0d0p1
/dev/cciss/c0d0p2
/dev/cciss/c0d0p3
/dev/cciss/c1d1
/dev/cciss/c1d1p1
/dev/cciss/c1d1p2
/dev/cciss/c1d1p3
/dev/fd0
/dev/hda
/dev/hda5
/dev/nb0
/dev/nullb
/dev/nullb0
/dev/pcd0
/dev/pda
/dev/pda1
/dev/pf0
/dev/pf1
/dev/ram0
/dev/ramX
/dev/rd/c0d0
/dev/rd/c0d1
/dev/rd/c2d5p3
/dev/rd/cCdD
/dev/rd/cCdDp1
/dev/rd/cCdDp7
/dev/st0
/dev/st1
/dev/zero
/dev/zram
/dev/zram0
/dev/zram1
/dev/zramX
```

**Comment by gombasg** [comment]
`ciss` is definitely a typo.

**Comment by jouvin** [comment]
I think I'm responsible of this regexp (at least the original one) in my early days in Quattor a long time ago...:smiley: I'm pretty sure it worked for the problem we had with HP device names at this time but it doesn't mean the regexp was correct. Thanks for spotting/fixing this.
