### ISSUE TITLE
Filesystem: mkfs.xfs should be used with -f

### ISSUE THREAD

**Issue by jouvin** [quattor/ncm-lib-blockdevices#90]
Without `-f` (not available in ext-related `mkfs`), `mkfs.xfs` refuses to recreate a file system if one already exists on the block device. With `-f`, it will ask a confirmation (no way to suppress it) if a filesystem is found.

**Comment by stdweird** [comment]
so in either case, no new filesystem (and using `-f` hangs the process wiating for answer?)

**Comment by stdweird** [comment]
this is an issue dueing ncm-filesystems or aii? aii should wipe the partitions (although some corner cases exist)

**Comment by jouvin** [comment]
@stdweird you are right, this is with AII and it hangs the process... It is certainly not a perfect solution but `lvcreate-y` also hangs the process (`-y` seems ignored with the `lvcreate` provided at installation time, it may be intentional...). But the real problem is that partitition wiping is far from being robust and it takes up to 3 or 4 reboot (normally happens automatically) to get the partitioning right and have the installer able to really install the system.... Note that the real issue may be the silently failing `dd` commands addressed by https://github.com/quattor/aii/pull/292... Probably need to sort this out first.

**Comment by stdweird** [comment]
aii partiton wiping will fail if you make subtle changes to the partiton layout or if anaconda failed (that's from memory, not sure what was the issue again), but an identical reinstall shouldn't fail. check the aii logs why and/or which partitons were trying to be wiped.

**Comment by jouvin** [comment]
In my case a reinstall with the same layout is failing 2 times before succeeding. It is partly caused by the fact that we have an LVM partition if I remember correctly. I also saw (but didn't troubleshoot) that `dd` towards the end of the partition was failing because it was exceeding the disk size... Thus  https://github.com/quattor/aii/pull/292... I don't think I'll be able to do more troubleshooting on this in the short term...
